FROM     ubuntu:16.04
MAINTAINER z [at] smartkit [dot] info

ENV DEBIAN_FRONTEND=noninteractive \
    ANDROID_HOME=/opt/android-sdk-linux \
    NODE_VERSION=6.11.1 \
    NPM_VERSION=5.3.0 \
    IONIC_VERSION=3.5.0 \
    CORDOVA_VERSION=7.0.1

# Install basics
RUN apt-get update &&  \
    apt-get install -y git wget curl unzip ruby ruby-dev gcc make && \

    curl --retry 3 -SLO "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" && \
    tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 && \
    rm "node-v$NODE_VERSION-linux-x64.tar.gz" && \
    npm install -g npm@"$NPM_VERSION" && \
    npm install -g cordova@"$CORDOVA_VERSION" ionic@"$IONIC_VERSION" && \
    npm cache clear --force && \

    gem install sass && \
    git config --global user.email "you@example.com" && \
    git config --global user.name "Your Name" && \
#    ionic start myApp sidemenu && \
WORKDIR myApp
EXPOSE 8100 35729
CMD ["ionic", "serve"]