version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '81:80'
      - '443:443'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mariadb
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '82:80'
      - '444:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - mediawiki   
  netlify:
    image: smartkit/godpaper-da-netlify:latest
    ports:
      - "80:80"
  jenkins:
    image: jenkins
    ports:
      - "83:8080"
      - "50000:50000"
    volumes:
      - 'jenkins_data:/var/jenkins_home'
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  piwik_data:
    driver: local
  jenkins_data:
    driver: local