version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  mediawiki:
    image: 'bitnami/mediawiki:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mariadb
  piwik:
    image: 'bitnami/piwik:latest'
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - 'piwik_data:/bitnami'
    depends_on:
      - mediawiki
  mediagoblin: 
    image: 'vky0/mediagoblin:latest'
    ports:
      - '5432:5432'
      - '6543:6543'
    depends_on:
      - piwik
volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  piwik_data:
    driver: local