apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_DATABASE
          value: bitnami_wordpress
        - name: MARIADB_USER
          value: bn_wordpress
        image: bitnami/mariadb:latest
        name: mariadb
        resources: {}
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: v1-mariadb-data
      restartPolicy: Always
      volumes:
      - name: v1-mariadb-data
        persistentVolumeClaim:
          claimName: v1-mariadb-data
status: {}
