apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: membersrvc
  name: membersrvc
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: membersrvc
    spec:
      containers:
      - args:
        - membersrvc
        image: hyperledger/fabric-membersrvc
        name: membersrvc
        ports:
        - containerPort: 7054
        resources: {}
      restartPolicy: Always
status: {}
