apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: uuid-accredit
  name: uuid-accredit
spec:
  ports:
  - name: "8095"
    port: 8095
    targetPort: 8095
  selector:
    io.kompose.service: uuid-accredit
status:
  loadBalancer: {}
