version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  #hyperledger    
  membersrvc:
    image: hyperledger/fabric-membersrvc
    ports:
      - "7054:7054"
    command: membersrvc
  vp0:
    image: hyperledger/fabric-peer:x86_64-1.0.0-rc1
    #image: hyperledger/fabric-peer
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    #container_name: v1_vp0_1
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=false
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc
    command: sh -c "sleep 5; peer node start --peer-chaincodedev"
  #mongodb  
  mongodb:
    image: smartkit/godpaper-go-mongodb
    ports:
      - "27017:27017"
    container_name: mongodb
  #activemq
  activemq:
    image: smartkit/godpaper-go-message-broker-activemq
    ports:
      - "1883:1883"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616"
    container_name: activemq
  #uuid-accredit
  uuid-accredit:
    image: smartkit/godpaper-go-uuid-accredit
    depends_on:
      - vp0
      - mongodb
    links:
      - vp0
      - mongodb
      - activemq
    ports:
      - "8095:8095"
    container_name: accredit
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/target/classes/AI_FILEs:/target/classes/AI_FILEs"
      - "/target/classes/sgf:/target/classes/sgf"
      - "sgf_data:/target/classes/sgf"
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
  sgf_data:
    driver: local
